### ISSUE TITLE
Examples & Installation

### ISSUE THREAD

**Issue by kirbyk** [nothingmn/pebble-api-dotnet#1]
@nothingmn can you add an installation and example(s) section to the README? We'd like to post it on the [developer website](http://developer.getpebble.com/guides/timeline/timeline-libraries/#pebble-api).

**Comment by nothingmn** [comment]
Done and done!

Cheers,

-Rob

**Comment by kirbyk** [comment]
Wow, that was super fast.

**Comment by nothingmn** [comment]
Yeah, easy when I just copied + pasted the unit tests into markdown.  :)
